# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 06:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import geoposition.fields
import mptt.fields
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', redactor.fields.RedactorField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaRepresiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='victimas.CategoriaRepresiva', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'Categor\xedas represivas',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name=b'eliminado')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Si lo deja en blanco se generar\xe1 a partir del nombre', unique=True, verbose_name=b'URL')),
                ('imagen', models.ImageField(blank=True, max_length=300, null=True, upload_to=b'%Y/%m/%d', verbose_name=b'Imagen principal')),
                ('descripcion', redactor.fields.RedactorField()),
                ('original_url', models.URLField(blank=True, null=True, verbose_name='Direcci\xf3n de los datos originales')),
                ('openrefine', models.CharField(max_length=255, unique=True)),
                ('github', models.URLField(blank=True, null=True, verbose_name='Github scrapy project')),
                ('num_records', models.PositiveIntegerField(default=0, verbose_name=b'N\xc3\xbamero de registros')),
                ('porcentaje', models.PositiveIntegerField(default=10, verbose_name=b'Porcentaje procesado')),
                ('administradores', models.ManyToManyField(blank=True, related_name='mis_datasets', to=settings.AUTH_USER_MODEL)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpeta', to='filer.Folder')),
                ('csv_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name=b'eliminado')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', redactor.fields.RedactorField()),
                ('tipologia', models.CharField(choices=[(b'publico', b'Documento p\xc3\xbablico'), (b'privado', b'Documento privado')], max_length=255)),
                ('tipo', models.CharField(choices=[(b'carta', b'Carta'), (b'registro', b'Registro'), (b'sentencia', b'Sentencia'), (b'foto', b'Fotograf\xc3\xada')], max_length=255)),
                ('formato', models.CharField(choices=[(b'texto', b'Texto'), (b'imagen', b'Imagen'), (b'video', b'Video')], max_length=255)),
                ('archivo', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HechoRepresivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fuente', models.CharField(max_length=100)),
                ('fiabilidad', models.CharField(choices=[(b'A', b'Hecho documentado'), (b'B', b'Testimonio directo'), (b'C', b'Testimonio indirecto'), (b'I', b'Indeterminado')], default=b'I', max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='victimas.CategoriaRepresiva')),
                ('datasets', models.ManyToManyField(blank=True, related_name='detalle_hechos', to='victimas.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('resumen', models.TextField(help_text='Peque\xf1o resumen de la licencia para mostrar en los listados')),
                ('uso', models.BooleanField(default=True)),
                ('difusion', models.BooleanField(default=True)),
                ('explotacion', models.BooleanField(default=True)),
                ('distribucion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name=b'eliminado')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', redactor.fields.RedactorField()),
                ('tipo', models.CharField(choices=[(b'P', b'Pol\xc3\xadtica'), (b'S', b'Sindical'), (b'R', b'Religiosa'), (b'C', b'Cultural')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name=b'eliminado')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[(b'H', b'Hombre'), (b'M', b'Mujer'), (b'U', b'Desconocido')], default=b'U', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_muerte', models.DateField(blank=True, null=True)),
                ('a_nacimiento', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'A\xc3\xb1o de nacimiento')),
                ('a_muerte', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'A\xc3\xb1o de muerte')),
                ('documento', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Pasaporte, DNI, etc')),
                ('estado_civil', models.CharField(choices=[(b'S', b'Soltero'), (b'C', b'Casado'), (b'V', b'Viudo'), (b'U', b'Desconocido')], default=b'U', max_length=100)),
                ('num_hijos', models.PositiveIntegerField(blank=True, default=b'U', null=True, verbose_name=b'N\xc3\xbamero de hijos')),
                ('estudios', models.CharField(max_length=255)),
                ('oficio', models.CharField(max_length=255)),
                ('nivel_socioeconomico', models.CharField(max_length=255)),
                ('ideologia', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('uso', models.BooleanField(default=True)),
                ('difusion', models.BooleanField(default=False)),
                ('explotacion', models.BooleanField(default=False)),
                ('distribucion', models.BooleanField(default=False)),
                ('afiliacion', models.ManyToManyField(blank=True, related_name='afiliados', through='victimas.Afiliacion', to='victimas.Organizacion')),
                ('datasets', models.ManyToManyField(blank=True, related_name='mis_registros', to='victimas.Dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[(b'fosa', b'Fosa com\xc3\xban'), (b'cementerio', b'Cementerio'), (b'lugar', b'Lugar'), (b'hospital', b'Hospital'), (b'campo_concentracion', b'Campo de concetraci\xc3\xb3n'), (b'campo_trabajo', b'Campo de trabajo')], default=b'lugar', max_length=100)),
                ('direccion', redactor.fields.RedactorField()),
                ('localizacion', geoposition.fields.GeopositionField(default=b'42.813127326939224,-1.6393232345581055', max_length=42)),
                ('datasets', models.ManyToManyField(blank=True, related_name='mis_lugares', to='victimas.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('geojson', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name=b'eliminado')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Si lo deja en blanco se generar\xe1 a partir del nombre', unique=True, verbose_name=b'URL')),
                ('imagen', models.ImageField(blank=True, max_length=300, null=True, upload_to=b'%Y/%m/%d', verbose_name=b'Imagen principal')),
                ('descripcion', redactor.fields.RedactorField()),
                ('visible', models.BooleanField(default=False)),
                ('administradores', models.ManyToManyField(blank=True, related_name='mis_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='Relaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[(b'X', b'C\xc3\xb3nyuge'), (b'C', b'Hijo'), (b'P', b'Progenitor'), (b'H', b'Hermano'), (b'O', b'Otro')], default=b'O', max_length=100)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='victimas.Person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pariente', to='victimas.Person')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='victimas.PlaceGeo'),
        ),
        migrations.AddField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mas_lugares', to='victimas.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='familiares',
            field=models.ManyToManyField(blank=True, related_name='parientes', through='victimas.Relaciones', to='victimas.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='lugar_enterramiento_definitivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterrado_en', to='victimas.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='lugar_enterramiento_muerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterrado_tras_muerte_en', to='victimas.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='lugar_muerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muertos_en', to='victimas.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='lugar_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nacidos_en', to='victimas.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='lugar_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residentes_en', to='victimas.Place'),
        ),
        migrations.AddField(
            model_name='hechorepresivo',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesos', to='victimas.Place'),
        ),
        migrations.AddField(
            model_name='hechorepresivo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hechos', to='victimas.Person'),
        ),
        migrations.AddField(
            model_name='hechorepresivo',
            name='victimario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victimario', to='victimas.Person'),
        ),
        migrations.AddField(
            model_name='document',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='victimas.Licencia'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='victimas.Licencia'),
        ),
        migrations.AddField(
            model_name='biography',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biografias', to='victimas.Person'),
        ),
        migrations.AddField(
            model_name='afiliacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_afiliados', to='victimas.Organizacion'),
        ),
        migrations.AddField(
            model_name='afiliacion',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_organizaciones', to='victimas.Person'),
        ),
    ]
